### ISSUE TITLE
Error running in Ios

### ISSUE THREAD

**Issue by rubenteste** [zesage/panorama#18]
Hi,
i'm running panorama in Ios, and give me this error when running the plugin:

======== Exception caught by image resource service ================================================
The following NoSuchMethodError was thrown by a synchronously-called image listener:
The getter 'mesh' was called on null.
Receiver: null
Tried calling: mesh

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _PanoramaState._updateTexture (package:panorama/panorama.dart:295:13)
#2      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:495:25)
#3      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:962:11)
#4      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:358:26)

**Comment by zesage** [comment]
try the last version v0.3.2
